import pandas as pd
df = pd.read_parquet("dataset/preprocessed/accommodations.parquet")
print("Columns:", df.columns.tolist())
print("\ndtypes:\n", df.dtypes)
print("\ncategory counts:", df["category"].value_counts().head(8).to_dict())
print("product_type counts:", df["product_type"].value_counts().head(8).to_dict())
print("star_rating NaN:", df["star_rating"].isna().sum())
print("price_in_aud NaN:", df["price_in_aud"].isna().sum())
print("lat NaN:", df["lat"].isna().sum())
print("Unique dest:", df["destination_display_name"].nunique())
print("Unique country:", df["country"].nunique())
print("Unique city:", df["city"].nunique())
print("provider counts:", df["provider"].value_counts().to_dict())
print("star_rating_score range:", df["star_rating_score"].min(), df["star_rating_score"].max())
print("guest_rating_score range:", df["guest_rating_score"].min(), df["guest_rating_score"].max())
